matrix:
  include:
    - language: python
      cache: pip
      python: "3.6"
      env: NAME=tests
      services:
        - postgresql
      install:
        - sudo apt-get install libpq-dev libgmp-dev libmpfr-dev libmpc-dev
        - sudo -u postgres createuser -s `whoami` || true
        - createdb zeus_test
        - pip install pipenv
        - pipenv sync --dev

      script:
        - pipenv run ./compile-translations.sh
        - pipenv run pytest -v --cov -n 2

      after_success:
        - pipenv run codecov

    - language: python
      cache: pip
      env: NAME=flake8
      python: "3.6"
      install:
        pip install flake8==3.6.0

      script:
        - flake8 --config=.flake8
