#!/bin/sh -e

PYTHON=/usr/bin/python2.7

if ! test -f "$PYTHON"; then
    echo "$PYTHON not found."
    exit 1
fi

if test -f env/bin/python && ! diff -q "$PYTHON" env/bin/python; then
    echo "env/bin/python is different than $PYTHON, recreating virtualenv."
    rm -rf env
fi

if ! test -f env/bin/python; then
    virtualenv --python="$PYTHON" env
fi

. env/bin/activate && pip install -r requirements.txt
