#!/usr/bin/env python3

import argparse
import secrets
import json
import string
import os


def main():
    parser = argparse.ArgumentParser(description='Generate a secrets.json file')
    parser.add_argument('filename', nargs='?', type=str)
    args = parser.parse_args()

    alphabet = string.ascii_letters + string.digits

    data = {
        'db_password': ''.join(secrets.choice(alphabet) for i in range(32)),
        'secret_key': ''.join(secrets.choice(alphabet) for i in range(32)),
        # TODO cryptosystem params
    }

    data_str = json.dumps(data, indent=2)
    if args.filename:
        with open(args.filename, 'w') as f:
            os.fchmod(f.fileno(), 0o600)
            f.write(data_str+'\n')
    else:
        print(data_str)


if __name__ == '__main__':
    main()
