# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-24 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecretAuthcode',
        ),
    ]
