# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-24 22:57


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeus', '0002_delete_secretauthcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectionInfo',
        ),
    ]
